### ISSUE TITLE
IP not displaying correctly

### ISSUE THREAD

**Issue by el3ctr0wqw1** [its-a-feature/Mythic#129]
Hello, i noticed that the IPs of the Active Callback Machines  are not displaying correctly sometimes it displays just the local ip , is there a way i can edit that so it can display the external ip 
after a little research i found a command that always displays the real ip, which is (wget -qO - icanhazip.com) can you show me which file to edit so i can add this command to the webUI

**Comment by its-a-feature** [comment]
Hey! So, when an agent checks in for the first time to Mythic, it sends along some of the information you see on the active callbacks page (username, host, pid, etc). Along with that, the agent sends in the local IP address for the machine. The agent can optionally include the external_ip address if it knows it, but it's not required. If you're wanting to run that `wget` command on the agent so that you can determine the external IP address there and then forward that along, you need to edit code in whatever agent you're using, not on the Mythic server. Running that command on the Mythic server will just get you the IP address of the Mythic server, which isn't what you're looking for.

The reason this sort of this is hard from the Mythic server perspective is that a lot of that data can get lost as you start to incorporate things like redirectors.  If you have agent ----> redirector ----> http c2 profile ----> Mythic, then Mythic can't simply look at the address of the last request it received because then it'll think that all external ips are the ip of the http c2 profile. If your redirectors include the xforwarded headers, then the http c2 profile will also properly forward those along to the Mythic server and you can get the proper external IP address that way.

**Comment by el3ctr0wqw1** [comment]
alright gotcha! , thank you for taking the time to answer and explain things.
