### ISSUE TITLE
Unable to delete files in "Downloads"

### ISSUE THREAD

**Issue by just1fi3d** [its-a-feature/Mythic#138]
V2.2.13

When attempting to delete files the popup comes up saying the "deleting" and the file line disappears for a second and then reappears.  The files are also not deleted from disk at Mythic/mythic-docker/app/files

**Comment by its-a-feature** [comment]
With the move to the new UI, I'm closing the issues for the old UI since it's no longer supported.  

The main branch of Mythic and the apollo, apfell. poseidon, leviathan, atlas, and service_wrapper agents have all been updated for Mythic v2.3.7. Next time you're able to do a fresh install of this version and leverage these agents, please reopen this issue if you encounter it in the new UI.
