### ISSUE TITLE
payload code to compile locally

### ISSUE THREAD

**Issue by ZerkerEOD** [its-a-feature/Mythic#185]
Is there a way to setup a payload then download the code used to compile locally on test? We have had test where we are blocked from downloading a .exe or executable file but we have been able to copy say c# and compile on the system locally. I am looking at Apollo right now and not seeing anything that resembles this. I ask because Covenant will give you the code to compile locally if needed.

**Comment by its-a-feature** [comment]
Hey! Um.. yes/no. I think it would be an option for each agent developer to expose a build parameter option to output a zip of source code with all dependencies rather than finished output. That being said, it's not too crazy to do yourself for any agent (you just have to consider that your build environment needs to match that of the docker container used by the payload). 

For Apollo specifically, the build process is here https://github.com/MythicAgents/Apollo/blob/master/Payload_Type/apollo/mythic/agent_functions/builder.py#L47-L190. That goes through getting all of the c2 profile parameters you specify in the UI, building the agent, and optionally running it through donut to make shellcode. The only non-intuitive piece here is that you need a UUID (https://github.com/MythicAgents/Apollo/blob/master/Payload_Type/apollo/mythic/agent_functions/builder.py#L72).

So, every time you build a payload within Mythic, that payload gets a new UUID that Mythic can use to track all sorts of information about the payload (c2 parameters, encryption, loaded commands, descriptions, etc). Naturally, that's not something you can just make up yourself and send to Mythic. So, you just need to build it once as you'd want through the UI, then on the payloads page you can see metadata for the payload which includes a UUID. Just use that UUID when you build offline and Mythic will be none the wiser.

**Comment by ZerkerEOD** [comment]
Thanks for the informaiton!
