### ISSUE TITLE
New payload builds saying 404 error.

### ISSUE THREAD

**Issue by Techno-Fox** [its-a-feature/Mythic#200]
It's me again. I don't know if it's because i recently did a git pull, or if it's something else, but for some reason, when ever i try building my payloads it gives 404, i was implementing the keylog function, when this started happening.

Debug data:
curConfig: (CallBackHosts: @["http://127.0.0.1:80"], Servers: @[(Domain: "http://127.0.0.1:80", Count: 0)], PayloadUUID: "8f3a2c2b-7962-4b8c-a127-9130cf0bb911", UUID: "", UserAgent: "USER_AGENT", HostHeader: "domain_front", Sleep: 10, Jitter: 23, KillDate: "2023-03-04", Param: "q", ChunkSize: 512000, DefaultProxy: false, ProxyAddress: ":", ProxyUser: "", ProxyPassword: "", GetUrl: "/index", PostUrl: "/data", Psk: "M4TDQeK2TRa7BDfvMC06MOxJjXr7VzYdKfSy1I120Fg=")

This request works:
http://127.0.0.1:80/index?q=OGYzYTJjMmItNzk2Mi00YjhjLWExMjctOTEzMGNmMGJiOTExWKO4z4Op%2FjrIHA5IZYe%2FLXqkuSjrzicF2iuIX2OlErbfThQMDsz2kAbI5zOHD8fh3BKAY7N4HQsM6i1LUarW86ZzfNsPxZDYlGbi9LQovVjP5dR6GxQZStEl%2FsBJu3x3RZZ5qy5n3RoYTmTwY9Q%2Fvp7azw%2FYllyInOWPY4G0kNFCgnjYL938wmSn3b04FiJKTU1YahK8zV2NOpajKK8IZWtqx0J%2FIUXsSXynvJDBSXoiS3VnPXKnIJOPBGdULtd%2B1gxiQPUbAsYR%2BiBlfH%2B1shrYYVUjaPMV4xAZbnSMTO42Q8Vh0ZB09JD%2BtgBWo9gJcZ6le2AREH9ZRKjnDhXW65sJheejGP4YVBCCKeQvIZH5BcYasUZVmaJx9MSI7iIECRboahLOvn4D6wYLJHkKT%2FpfTR16ppGQTuy1DlLWGCU%3D

Debug data:
curConfig: (CallBackHosts: @["http://127.0.0.1:80"], Servers: @[(Domain: "http://127.0.0.1:80", Count: 0)], PayloadUUID: "e3856d96-b74c-4c81-a58e-037b260db5be", UUID: "", UserAgent: "USER_AGENT", HostHeader: "domain_front", Sleep: 10, Jitter: 23, KillDate: "2023-03-24", Param: "q", ChunkSize: 512000, DefaultProxy: false, ProxyAddress: ":", ProxyUser: "", ProxyPassword: "", GetUrl: "/index", PostUrl: "/data", Psk: "SU300fFBVv/z7GjxDBSrG+aRC6KFIkwzol3bRPuzLpo=")

Reqeust that doesn't work?
http://127.0.0.1:80/index?q=ZTM4NTZkOTYtYjc0Yy00YzgxLWE1OGUtMDM3YjI2MGRiNWJl2%2BXfSAhDUw4S8EHfk4SPKyY3XvWfuC9VSd8jwenRdjc1F4lSxyXe0u6OhVqh6SwhSOwLZM0g0hrJVlA8nymN%2F%2BcMTMw4D7h%2FwuqBguGj1YHC%2BnjOmrdiLYdk4ROOF1b3uqkbJe8q5oquTIdGuH2vbSo%2B1oWqPMXf7bfMVER9ZrqFXlyCZhS8zJ6kNs2YJkV3I1beKnedAOs5n1Ua02YI%2F7ByFCcIVsCCkIuTx%2BXSIHeM%2BiQiVIruYnnVO2icJtLajWMcIBgSVs0XOxZ8LYR9ixVbdgJivfgO7UUsxGLX%2BPl%2Ff5%2F8Sa2mFX4wXPuHRD%2FlHvI1Z4SVEyxhPGJTugxJXpoaMy5Svxtfvk47peGenJ49rGNcfEMMuHOcgadrPbovuJpFQkFFxXLbZES%2BzQNhqhmx6mqnTRCEzh9RASVJpLU%3D

I've tried rebuilding multiple times, but it keeps giving me this error. When I use old versions of the payload it works, but i changed nothing with the checkin, or http. I've even removed the keylog function, and still doesn't work. Is something wrong with the requests?

**Comment by its-a-feature** [comment]
Is it when building a payload or when you send a message from your agent to Mythic? 

The requests you shared don't help because they're not plaintext (https://gchq.github.io/CyberChef/#recipe=URL_Decode()From_Base64('A-Za-z0-9%2B/%3D',true)&input=WlRNNE5UWmtPVFl0WWpjMFl5MDBZemd4TFdFMU9HVXRNRE0zWWpJMk1HUmlOV0psMiUyQlhmU0FoRFV3NFM4RUhmazRTUEt5WTNYdldmdUM5VlNkOGp3ZW5SZGpjMUY0bFN4eVhlMHU2T2hWcWg2U3doU093TFpNMGcwaHJKVmxBOG55bU4lMkYlMkJjTVRNdzREN2glMkZ3dXFCZ3VHajFZSEMlMkJuak9tcmRpTFlkazRST09GMWIzdXFrYkplOHE1b3F1VElkR3VIMnZiU28lMkIxb1dxUE1YZjdiZk1WRVI5WnJxRlhseUNaaFM4eko2a05zMllKa1YzSTFiZUtuZWRBT3M1bjFVYTAyWUklMkY3QnlGQ2NJVnNDQ2tJdVR4JTJCWFNJSGVNJTJCaVFpVklydVlublZPMmljSnRMYWpXTWNJQmdTVnMwWE94WjhMWVI5aXhWYmRnSml2ZmdPN1VVc3hHTFglMkJQbCUyRmY1JTJGOFNhMm1GWDR3WFB1SFJEJTJGbEh2STFaNFNWRXl4aFBHSlR1Z3hKWHBvYU15NVN2eHRmdms0N3BlR2VuSjQ5ckdOY2ZFTU11SE9jZ2FkclBib3Z1SnBGUWtGRnhYTGJaRVMlMkJ6UU5ocWhteDZtcW5UUkNFemg5UkFTVkpwTFUlM0Q). 

Are you able to share the final JSON messages that are being sent?

When Mythic gets a message it doesn't understand from an agent, it sends back an empty response with a 404 error code, but it should log what the error was with the message. Check out `sudo ./mythic-cli logs mythic_server` when that happens to see some error information.

**Comment by Techno-Fox** [comment]
Saying MAC check failed

[2022-03-25 14:53:29 +0000] [31] [ERROR] crypto.py: MAC check failed
Traceback (most recent call last):
  File "/Mythic/app/crypto.py", line 52, in decrypt_message
    decrypted = await decrypt_AES256(
  File "/Mythic/app/crypto.py", line 127, in decrypt_AES256
    h.verify(mac)
  File "/usr/local/lib/python3.8/site-packages/Crypto/Hash/HMAC.py", line 165, in verify
    raise ValueError("MAC check failed")
ValueError: MAC check failed
[2022-03-25 14:53:29 +0000] [31] [WARNING] callback_api.py - 367 MAC check failed

**Comment by Techno-Fox** [comment]
Yep, i fat fingered in my crypto function. Thank you for letting me know how to look at logs. I'm sure that will be handy in the future.
