### ISSUE TITLE
CLI command parsing does not correctly handle dashes

### ISSUE THREAD

**Issue by just1fi3d** [its-a-feature/Mythic#203]
Mythic v2.3.7

I'm developing an agent command to with args that may contain dashes and it appears that the CLI parsing of them is incorrect.
Ideally I would like to receive two parameters (path and args). 

The following commands are prevented from even running by an error popup stating "**Too many positional arguments given. Did you mean to quote some of them?**":
`run ping -c 1 google.com`
`run ping "-c 1 google.com"`
`run "ping" "-c 1 google.com"`

If I try to run the command with named arguments I am able to run them but self.command_line contains the wrong values. The below commands result in `self.command_line == {"path":"ping","args":"","c 1 google.com":true}` in parse_arguments. As you can see args remains unpopulated and the dash has been stripped from the args string.
`run -path "ping" -args "-c 1 google.com"`
`run -path ping -args "-c 1 google.com"`

It appears this incorrect parsing may be happening client side as I watched the requests to graphql createTasking and saw the following:
```
command	"run"
original_params	"-path ping -args \"-c 1 google.com\""
params	"{\"path\" : \"ping\",
                  \"args\" : \"\",
                  \"c 1 google.com\":true}"
tasking_location	"parsed_cli"
```

It appears original_params is correct and params is the is the incorrect value I saw when testing with named parameters. It's worth noting that if the parameters are entered via the modal popup everything works correctly. This issue appears to only be with the CLI.

**Comment by just1fi3d** [comment]
Just got a chance to test this morning.  It looks like it parses the dashes correctly with equals signs but I'm seeing some other weird behavior with slashes being inserted.  
`run -path="ping" -args="-c 1 google.com"` results in ` 'command_line': '{"path":"\\"ping","args":"\\"-c 1 google.com"}'`

It's worth noting that raw_command_line has the correct values in these cases but I'm guessing that's because it isn't parsed at all. For example:
`run -path ping -args "-c 1 google.com"` results in `'command_line': '{"path":"ping","args":"","c 1 google.com":true}', 'raw_command_line': '-path ping -args "-c 1 google.com"'`

**Comment by just1fi3d** [comment]
Also, I can confirm the following is what I have set up.

> assuming you have path as ui_position=1 and args as ui_position=2

**Comment by its-a-feature** [comment]
Ok, I just pushed an update to the v2.3-testing branch. Can you pull that version and test it out with your command? The library I was using has a lot of nice features, but cannot seem to properly handle the starting `-` in values for arguments. So, I just ripped out the library and re-implemented the functionality I use. So, all of the following should now work with that branch:

run ping "-c 1 google.com"
run -path ping -args "-c 1 google.com"
run -path "ping" -args "-c 1 google.com"
run ping -args "-c 1 google.com"
run -path ping "-c 1 google.com"
and technically in this instance with how you have things set up, even this should now work `run ping -c 1 google.com` because `ping` will get parsed into your `path` parameter and the rest will get grouped together for your final remaining parameter, `args`. 

Since I'm taking full control of how this parsing is now happening, I'm currently not going to support the `=` method since i think that's a bit less intuitive for people when normally thinking about CLI parsing.

**Comment by its-a-feature** [comment]
The UI should report version 0.0.45 at the bottom when you click the hamburger icon on the top left

**Comment by its-a-feature** [comment]
Ok, just made a new push that should address the logic. I was only stripping the quotes for the last argument lol that should be addressed now

**Comment by just1fi3d** [comment]
Yup looks like that fixed it haha! Thanks for the support on this. Closing it.
