### ISSUE TITLE
Task Autocomplete Not Showing

### ISSUE THREAD

**Issue by eth0-re** [its-a-feature/Mythic#239]
Thoroughly impressed so far!

Only issue I've hit so far is the text/command entry field doesn't seem to be autocompleting in v2.3.9.
For example if I type `wh` I would expect to see the suggestions containing `wh` like `whoami`, but there's no suggested commands. 

This is on the page: https://127.0.0.1:7443/new/callbacks
Revering to the old UI: https://127.0.0.1:7443/callbacks shows the autocomplete working fine

I've checked the following locations:
* The HTML and it doesn't look like there is a dialog being populated but remaining hidden. (No instances of 'whoami' in the HTML)
* Using the React devtools I can see there's 2 components that are loaded, so the data is being initially requested and stored in React
  * The first one "message" which contains the current value of the task search
  * The second "loadedOptions" which contains all the possible commands

![2022-07-08_075346](https://user-images.githubusercontent.com/73724048/177934310-de06941a-881e-4628-bed5-2c48f3131f25.png)

Didn't know this was a feature until I saw it in your video 😂 I'd definitely love to get it working in the new UI: https://youtu.be/SYvDqZqgqm&t=145

**Comment by its-a-feature** [comment]
Hey! Great question. This is one of the things that changed between the old and new user interfaces. Instead of showing a popup as you're typing, the new UI has tab-complete. So, if you type `wh` and hit tab, you can cycle through all of the commands that start with `wh`. This also applies to any parameters for that command. So, if you have a command `whoami` that takes two parameters, `all` and `groups` for example, then you can do `whoami +tab` and start cycling through all of the parameters for that command. Additionally, you can do `ctrl+r` to do a reverse grep search through previous commands to find one you want to execute without having to keep hitting the up/down arrows.
