### ISSUE TITLE
Feature request: Allow downloads with undefined number of chunks

### ISSUE THREAD

**Issue by SanderUbink** [its-a-feature/Mythic#249]
**Context**
I am currently building an agent for which I would like to incorporate support for native Cobalt Strike Beacon Object Files (BOF's). The download functionality for Cobalt Strike works in three steps:
1. Open a file
2. Write file chunks
3. Close the file

This implementation does not require knowledge of the number of chunks when opening the file. The Mythic implementation for file downloads does require this knowledge. As such, it is not possible to support the native file download functionality of existing BOF's without internally buffering the file.

**Feature request**
Add support for the three step approach for downloading files (open, write, close), such that the number of chunks does not need to be known at the time of opening of the file.

**Comment by its-a-feature** [comment]
Hey! Great request! I have a few questions though:

- Mythic requires that for file downloads that you first send a message to Mythic indicating your intent to download a file so that it can return a file UUID back to the agent. The agent then uses that UUID as part of its messages so that Mythic knows which file that data is for. Is this still something you're able to do? Outside of the BOF perhaps?
- You don't have to fully buffer the file to know how many chunks there are; you can use API calls to get the file size and then just divide by the size of each chunk you're doing.
- Mythic also supports additional metadata to be sent with file downloads to report back the full path of the file being downloaded. For example, tasking `download test.txt` doesn't let Mythic know _where_ `test.txt` is on the file system. Is this something you're also able to support?

If you're still able to do the first one, then I could add in a flag or some other piece of information that would allow you to specify that you don't know the total number of chunks. You'd still need some way to indicate to Mythic that the file is done transferring. Are you able to send a message after transferring all of the data to tell Mythic that the file is done? I ask specifically about file completion and not task completion because there can easily be situations where in a single task you're transferring back multiple files.

**Comment by SanderUbink** [comment]
Hey, thanks for the quick reply.

- Yes, it is not a problem to indicate that a file is about to be transferred in the first message. The only problem with the initial message is the total_chunks field.
-  The problem with this lies in the fact that the intended usage of the download functionality does not actually concern "files". Instead, what it refers to is user output that the operator wishes to store in a file on the team server, rather than show fully to the operator. An example is the BOF [nanodump](https://github.com/helpsystems/nanodump), which creates a dump of LSASS in-memory and writes that dump directly to a file on the team server, without touching the disk of the compromised system. Cobalt Strike offers API functions for sending output from the BOF to the team server, which support three output types related to file downloads (open, write, close). Hence, existing BOF's do not call the output API functions with a total number of bytes. Instead they call the output function multiple times with type "write" to write individual chunks. After all bytes  have been transferred, a final call to the output API is made, signaling that the file transfer is complete. To support these BOF's in a Mythic agent, the agent would have to buffer each call to the output API to be able to calculate the total number of chunks that is required.
- In terms of this issue, metadata is not really relevant. The intended functionality is mostly aimed at writing bytes from memory directly  to a file on the team server. Including a full path does not pose any problems, but it also doesn't help solve the issue at hand.

What I would basically need is:

- Being able to start a file transfer without specifying the number of chunks
- Being able to signal to the server that a chunk is the last chunk of a file

**Comment by its-a-feature** [comment]
ah gotcha. Yeah, that's definitely doable. I'm currently rewriting the back-end into Golang, so I'll add this functionality into that, which means you'll see this around the end of the year when I finish up all of that work.

**Comment by its-a-feature** [comment]
This is doable in the latest Mythic - simply supply a negative value for your `total_chunks` when doing your initial registration, then when you have an idea bout your total number, simply add it along with your chunk data and Mythic will update the file accordingly.
