### ISSUE TITLE
Automatic tasks for new callbacks

### ISSUE THREAD

**Issue by XCVYN6UGT85JywuH** [its-a-feature/Mythic#262]
Hello! Is there a way to create automatic tasks for new callbacks?

I want to create automatic task for new callbacks if build parameter for their payload was set to "True".

Sorry if this is a dumb or already answered question. I have read all issues and documentation, but found nothing what can help me. Maybe i missed something.

**Comment by its-a-feature** [comment]
Hey! Yup, there is! You'll just have to tweak this slightly, but the general documentation for the new scripting is on the PyPi README (https://pypi.org/project/mythic/) - I need to move it into the documentation and remove all of the old REST interfaces with the upcoming release in Q1. 

```
my_custom_subscription = """
 subscription MySubscription {
  callback_stream(batch_size: 1, cursor: {initial_value: {init_callback: "1970-01-01"}}) {
    payload {
      buildparameterinstances(where: {buildparameter: {name: {_eq: "buildparam1"}}}) {
        value
      }
    }
  }
}
"""
async for data in mythic.subscribe_custom_query(
   mythic=mythic_instance, query=my_custom_subscription
):
   # do something with the data
   print(f"[*] Got data:\n{data}\n")
  pass
```
of course you can swap out `init_callback` value with the current timestamp and the name of the build parameter instead of `buildparam1`, but you'll get back a dictionary in `data` that matches that format:
```
callback_stream[0]["payload"]["buildparameterinstances"][0]["value"]
```
where `callback_stream` is an array and `buildparameterinstances` is an array. 
If you're curious about doing your own custom things like this, I highly recommend checking out `/console` in the Mythic UI and getting the `HASURA_SECRET` from your Mythic's `.env` file. Then you can play around with the scripting to your heart's content and run exactly what you want to do first to make sure everything comes back as expected before putting it into a script. 

In the next update of Mythic in Q1, Mythic will optionally include a Jupyter notebook to help with this sort of thing and allow me to more easily provide up to date examples

**Comment by XCVYN6UGT85JywuH** [comment]
Ok, i will write python script that will listen for new callbacks and create new tasks automatically.
Then i will run this script on my host with my mythic user credentials. And until this script is running automatic tasks will be created for all new callbacks. But what if new callback will happen when my host is shutdown? Do i need to run this script permanently on server?
What is the best way to integrate this functionality in my payload container? I mean, it must not be a temporary solution.

**Comment by its-a-feature** [comment]
if you want it to run all the time, what you could do is just have the script run on the server or, for even more stability, bundle it into its own docker container and have that running somewhere as well. 

With the update in Q1, there will be a Jupyter Notebook docker container that you can use to run those sorts of long-running scripts

**Comment by XCVYN6UGT85JywuH** [comment]
Ok, thank you.
