### ISSUE TITLE
Getting an error after getting mythic repo update 3.0.0, setup has broken

### ISSUE THREAD

**Issue by Akshayraje7** [its-a-feature/Mythic#287]
Getting an error after getting mythic repo update 3.0.0, setup has broken.
Earlier, it was able to install config http c2 profile but now it is not getting installed.
Also it is showing rabbitmq is not online, how to fix it? i have two setups - one is on 2.3.13 and another is on 3.0.0.

3.0.0 is showing no command found whentrying to start  Mythic_CLI
2.3.13 showing Rabbitmq server is not connected, also not able to install config http c2 profile
<img width="592" alt="image" src="https://github.com/its-a-feature/Mythic/assets/133856353/f6905367-0f8c-4c94-85d6-b6f7f2db29c2">

**Comment by its-a-feature** [comment]
Right now, you can't run two instances of Mythic at the same time because they share container names.

As of May 10, all of the master/main branches moved to Mythic 3.0. So, on a Mythic 2.3 install, you can't run `./mythic-cli install github <url>` without pulling the Mythic 3.0 version. I'll try to go through and make a branch that can be used with Mythic 2.3 for all the repos that can be used instead. 

To get Mythic 3.0 up and going, you should do the following in your Mythic 3.0 folder:
```
make (this will generate the mythic-cli binary)
docker system prune -a (this will remove ALL images on your system so be careful if Mythic isn't your only thing on there)
./mythic-cli database reset (this will clear out everything in your mythic 3.0 database)
./mythic-cli start
```

**Comment by its-a-feature** [comment]
I'm going to assume this was fixed and close it, if you're still having an issue though, let me know and reopen it
