### ISSUE TITLE
Webhooks not working in 3.0

### ISSUE THREAD

**Issue by 0ca** [its-a-feature/Mythic#290]
Slack notifications are not working on 3.0, they work in 2.x.

I configured the Webhook URL and the channel in the operation edit page. But I don't get any notification when I get a new callback.

I tried to trigger a callback from `/new/consuming_services`, with `New Callback Webhook`, but when I click I get an error:
```
Failed to deliver message to exchange/queue. Error code: 0, Error Text:
```

Also, I liked that in 2.x you could customize the content of the notification, so I could include fields like hostname and username. Could it be possible to bring that feature back? 

Thank you so much for your work!

**Comment by its-a-feature** [comment]
Hey! Great question! In Mythic 3.0, webhooks were removed from the main mythic_server and split out into a separate container. Technically, any agent or c2 profile code can do their own webhooks, but there's also a `basic_webhook` container here: https://github.com/MythicC2Profiles/basic_webhook.

So, the general flow would be:
1. install agents and c2 profiles
2. install `./mythic-cli install github https://github.com/MythicC2Profiles/basic_webhook`
3. continue on as normal

Webhooks now have the option for separate channels for:
* mythic starting
* alert messages
* new callbacks
* feedback messages
* custom webhook data from scripting

Those are all the different "options" to test that you see in the UI for the consuming services page. When you set the webhook URL and Channel in the UI, you're essentially setting a "default" in case nothing else was configured specific to the webhook containers. In your `Mythic/.env` file you see a bunch more settings for configuring the channels and webhook urls.

Additionally, since it's all broken out into its own container, you have full control over the message formats. If Golang isn't your preferred language, there's also examples in Python (https://github.com/MythicMeta/ExampleContainers/blob/main/Payload_Type/python_services/mywebhook/webhook.py) that you can use too.

**Comment by its-a-feature** [comment]
This also makes it much easier for you to send webhooks to multiple channels, slack spaces, or even to other 3rd party servies. Since you have full control, you can even hook it up to internal services that require additional authentication. This style also means that you have access to the SendMythicRPC* suite of functions for additional enrichment for callbacks/tasks to give more context for your webhooks
