### ISSUE TITLE
Mythic Socks Issue RabbitMQ

### ISSUE THREAD

**Issue by oliviapa001** [its-a-feature/Mythic#321]
There appears to be an issue with my install of Mythic I'm not able to use Socks proxy on Medusa Agent:

[*] Mythic Local Version:  v3.0.1-rc45
[*] Mythic Remote Version: v3.0.1-rc45
[+] Mythic is up to date!
[*] UI Local Version:  v0.1.15-rc38
[*] UI Remote Version: v0.1.15-rc38
[+] Your UI is up to date!
[*] mythic-cli Local Version:  v0.2.1
[*] mythic-cli Remote Version: v0.2.1
[+] Your mythic-cli is up to date!

Getting these from mythic_server logs

{"level":"error","error":"EOF","func":"github.com/its-a-feature/Mythic/rabbitmq.(*callbackPortUsage).**handleSocksConnections.func2**","line":456,"server_id":216347703,"time":"2023-07-28T18:09:30Z","message":"Failed to read from connection, sending exit"}

As a result I'm not able to proxy my traffic through designated socks proxy.

**Comment by its-a-feature** [comment]
I believe this is an issue with the Medusa agent specifically. This line in the `socks` command (https://github.com/MythicAgents/Medusa/blob/master/Payload_Type/medusa/medusa/mythic/agent_functions/socks.py#L100) sets the task as finished (status = success), so it never actually goes down to the agent for processing. 

I'm not sure if you're in the BloodHound Slack's #mythic channel, but somebody else noticed this a few months ago too. The fix is to just go to `Mythic/InstalledServices/medusa/medusa/mythic/agent_functions/socks.py` and edit that line (also edit the corresponding piece about stopping socks so that it's not completed and actually goes down to the agent). Then run `./mythic-cli start medusa` to restart the container and load up your changes to that python file (no need to generate a new agent).
