### ISSUE TITLE
Better Host Tracking - Host UUIDs

### ISSUE THREAD

**Issue by runesage** [its-a-feature/Mythic#327]
Would be useful if we could better track unique hosts and deconflict on device UUIDs rather than hostname. Ran into an instance where was doing a CTF and there were multiple unique machines with the same hostnames. Lead to making things complicated to figure out which device was what with some backend scripting.

It would like be a fundamental rewrite with a lot of the backend schemas so maybe longer term for like 4.0 release but maybe replicating something like what [sliver has done here](https://github.com/BishopFox/sliver/tree/master/implant/sliver/hostuuid). This could provide a better way to track systems compared to just relying upon the hostname.

**Comment by its-a-feature** [comment]
Interesting. So, if I'm tracking correctly, you had a CTF environment where you had multiple duplicate hosts (like two `ABC.DOMAIN.COM`) because you had agents in different, cloned environments. You were able to task and do everything fine, but when it came to the data that was aggregated by Mythic on the back-end (processes, file browser), that data got convoluted because it was technically multiple different host data squished together?

So, you're looking for a way to collect all that data, but still have a way to identify one `ABC.DOMAIN.COM` from the other cloned `ABC.DOMAIN.COM`? You were doing this with scripting right? Did the hosts have anything unique about them (ex: IP ranges were different subnets based on team number)?

**Comment by runesage** [comment]
The gist was for the “routers” they set up in the environment that were in scope for the entities of the event were all vyos so several devices had “vyos” as the hostname, no domain. It looks as though mythic tracks uniqueness based upon the hostname so when looking at data it collated things from different devices. If someone looked at the file browser for example via the web interface it got convoluted to see multiple devices smashed together without looking at which agent generated the data. They had different ip’s so we could technically do it that way.

**Comment by its-a-feature** [comment]
Ah yeah, that's definitely a harder problem to solve. Mythic does track which agent reported the data for the file browser or process browser, but identifying host uniqueness is definitely tough. It's one thing if you have an agent on the target and can report back some combined UUID/hash (that'll uniquely identify the host from a cloned instance but stay the same across a reboot), but it's more difficult if you start considering remote listings (ex: `ls \\abc.domain.com\admin$\test`). Was your main experience with this through the file browser or through scripting? Because Mythic knows _where_ the data originally came from, I could add an option in the file/process browser to essentially filter down what you see based on a certain callback's data as a short-term solution.

**Comment by runesage** [comment]
I was mostly considering the former situation (you have an agent vs remote shares). Primarily thinking of more general `ls` usage for file browser or process browser usage. We were using both file browser and scripting. I ended up being able to do a workaround with scripting by cross correlating the agents and handling the host deconfliction that way. The file browser on the gui smashed all three devices under one entity as well for those not comfortable scripting out data so that wasn't usable to them.

Based upon the mythictrees DB Schema we are tracking only via hostname which lead to the less than helpful behavior. I think inclusion of a "UUID" field within the callback schema and requiring agents to report that via a standarized format could help provide more meaningful context to hosts? Some of the other fields like mythictrees could reference the UUID and this would help clean up some of the other aspects like file/process browser, not requiring workarounds to figure out which mythictrees go to which box. That could also fix up some of the api's like get_unique_compromised_hosts.

I suppose however this could also be moot given an environment may just use VM Clones leaving the system UUIDs the same across devices derived from the base image. Happy to debate/discuss options however regardless both short term and long term.

**Comment by its-a-feature** [comment]
I think I have a fix for this (provided a demo video in the #mythic channel within the Bloodhound Slack if you're a member there). Hoping to push it out tomorrow.

**Comment by its-a-feature** [comment]
this is pushed in the latest version of Mythic now

**Comment by timukas** [comment]
I've played a bit with several cloned VMs and tried to find "uniqueness".

For Centos 7.9 x64 **hostnamectl** shows same Machine ID for all cloned VMs.

![image](https://github.com/its-a-feature/Mythic/assets/1915618/c04e3fa0-5947-4005-a581-c1fb879b7de3)

But Boot ID is unique. After reboots, Machine ID stays the same, but Boot ID was unique on all machines during tests i've done.

**Comment by its-a-feature** [comment]
You'd need something that's also consistent across linux, windows, and macOS. Considering that Mythic also allows agents like chrome extensions, determining "unique" host becomes even harder. 

The solution I pushed to Mythic takes a different approach and still relies on hostname, but a hostname + callback id combo. This leaves it up to the operator to just edit the groups associated with a callback and thus edit how data is merged in the file browser and process browser views.

**Comment by its-a-feature** [comment]
I'm gonna close this one since the host+callback tracking seems to address this specific issue
