### ISSUE TITLE
Are you still using maroto?

### ISSUE THREAD

**Issue by johnfercher** [its-a-feature/Mythic#337]
Hello, how are you?

I saw through github that this repo use [johnfercher/maroto](https://github.com/johnfercher/maroto) to generate PDFs. But navigating in the repo I only saw a mention in a [LICENSE](https://github.com/its-a-feature/Mythic/blob/00b7b635fb60301ecbfea1e75502ac92debeac40/mythic-docker/src/LICENSE#L48-L67) file. 

If you still uses maroto, I would like to purpose to use your project as a pilot to [maroto v2](https://maroto.io/#/README), which just reach a beta version. The internal core still almost the same, but the API was re-designed to allow many more features. It runs at least twice as fast than v1 and supports unit tests.

**Comment by its-a-feature** [comment]
I tried using it when I initially did a rewrite of this project to Golang, but I couldn't get it to work properly for my needs. I ended up using Golang's structure tagging capabilities to generate HTML instead of a PDF. 

If I remember correctly, I had issues with long text in table cells needing to be word wrapped and it causing issues. I also can't remember if I got hyperlinks to work correctly or not.
