### ISSUE TITLE
Weird behavior in "Process Browser" and "File Browser".

### ISSUE THREAD

**Issue by timukas** [its-a-feature/Mythic#341]
Hello,

Using latest mythic (also latest http & poseidon) on Linux x64.

I've created and started same ELF x64 payload on 3 different machines.
Machines have hostnames R1, R2 and R2 (ips are different).

![image](https://github.com/its-a-feature/Mythic/assets/1915618/aea03b01-2a4c-434a-84e1-5bbb11ce7d49)

Next, from each callback session i run native 'ps' command and i see output under each active session.

Now when i open 'Process Browser' i see only 2 hosts - R1 and R2.
R2 process view shows 'ps' output for last active callback with same hostname.

![image](https://github.com/its-a-feature/Mythic/assets/1915618/a06857f8-6c33-4563-b0ca-6d0820678362)

And when i exit and hide the callback (R1) it still appears in "Process Browser" list. Shouldn't it be hidden from list if session is hidden/exited?

Also strange thing happens to "File Browser". I run native 'download /etc/resolv.conf' command on all 3 active callback sessions. Downloaded file is visible under each session.
But when i open 'File Browser' i see only 1 host 

![image](https://github.com/its-a-feature/Mythic/assets/1915618/86b4c043-f2cf-430d-b6b7-8136c34ecc13)

Any ideas on that?

P.s. imho, this issue might be somehow related to #327.

**Comment by its-a-feature** [comment]
I think you're right that it's related to the other issue. Mythic currently tracks and merges data for the FileBrowser and ProcessBrowser by hostname, which is why your two different `R2` hosts are getting squished together. You should see two hosts for your FileBrowser view though, `R1` and `R2`. When you download that file from your `R1` callback, can you then run `sudo ./mythic-cli logs mythic_server` to see if there's any error getting reported that might be preventing it from showing up in the UI? 

Also something else to note: When you exit/hide a callback, it does _not_ remove all of that session's associated data. So even if you hide/exit that callback, i wouldn't expect anything to change in the FileBrowser or ProcessBrowser views. 

It's on my list of things to do to support better tracking for that scenario (also see it in things like CCDC competitions). It's easy-ish enough to track by hostname + ip, but the tough part comes in when you do something like `ls \\R2\C$` - which of the two `R2` hosts is it referring to, or is it a new, different `R2` host. I'd have to keep it separate and provide a new series of buttons in the UI to allow you to force merge things that you know refer to the same host.

**Comment by its-a-feature** [comment]
I think I have a fix for this (provided a demo video in the #mythic channel within the Bloodhound Slack if you're a member there). Hoping to push it out tomorrow.

**Comment by timukas** [comment]
This new grouping feature is cool. Simplifies many things if you have identical hostnames.

One thing could be added - sorting of available groups in the dropdown menu.


![image](https://github.com/its-a-feature/Mythic/assets/1915618/faadebc9-0468-4b37-b676-cb51c3e688c7)

**Comment by timukas** [comment]
Noticed one issue/bug with recent grouping add-on in UI.

If you pick 'File Browser' from any callback (callback-30 in my case), then new tab is opened and you see list of files/folders from each host (based on groupings) where file listing was done earlier. This is cool, works as it should (imho, A-Z sorting of groups can be added to the view)

![image](https://github.com/its-a-feature/Mythic/assets/1915618/5f7391eb-c009-49ad-886c-0cb5e17fb432)



Now if you run 'Task Listing' on folder for any machine (callback-19 in my case), it's being executed only on callback from where you opened file browser (callback-30 in my case).

![image](https://github.com/its-a-feature/Mythic/assets/1915618/b37cff47-cc08-45c0-867c-6a178adc2450)

![image](https://github.com/its-a-feature/Mythic/assets/1915618/37568837-c989-4358-bc1d-81cbd745af76)

**Comment by its-a-feature** [comment]
Ah yeah, I can add sorting of those group names (for file and process listing).

**Comment by its-a-feature** [comment]
If you open the file browser under callback 30, then all taskings will get issued under callback 30 (this is intended). 

A while ago I actually had it default to the callback that originally returned that data (so it would have been callback 19 in your case); however, over time you have more and more dead callbacks, so you needed to manually specify some _other_ callback to run the task through (if at all). This resulted in more complexity than many people were willing to deal with and just wanted everything executed through the context where you opened the file broweser

**Comment by its-a-feature** [comment]
Just pushed a new UI version, 0.1.33, that sorts the groups and the hosts within each group for the file browser and process browser

**Comment by timukas** [comment]
Updated to UI 0.1.33.

Sorting  of groups in Processes and File Browser now works.


![image](https://github.com/its-a-feature/Mythic/assets/1915618/c0295276-cbd3-4890-a133-5ee0ad7540f1)

P.s. What is the correct way to update UI?

```
git pull
make
./mythic-cli restart
```

Or there're some other specific things which must be done for proper update/upgrade?

**Comment by its-a-feature** [comment]
Since this is working now, I'm gonna go ahead and close this one
