### ISSUE TITLE
Active callbacks Host column filter misleading.

### ISSUE THREAD

**Issue by timukas** [its-a-feature/Mythic#349]
Hello,

In main callback view all hosts are written in uppercase.

![image](https://github.com/its-a-feature/Mythic/assets/1915618/0e3a1316-adf3-4ebd-9089-d5ba36bd6c8b)

When you filter host column by 'TLE' or 'WWW', then nothing is displayed.

From callback metadata you can see, that real hostname (2) is in lowercase and Host value (1) is in uppercase:

![image](https://github.com/its-a-feature/Mythic/assets/1915618/e85f5ced-a8b9-448b-a9c7-d6cf116865ac)

So it came out, that host filtering works only for lowercase hostnames.

And Last checkin filtering also behaves weirdly. If i set filter to 22, then i see this:

![image](https://github.com/its-a-feature/Mythic/assets/1915618/acd3bd64-6750-40b1-b72b-845b7fd9723e)

I've played with different numbers there and could not find any explanation how filtering work for last checkin column.

**Comment by its-a-feature** [comment]
Just addressed both of these with UI version 0.1.35. 
* host filtering was normalizing the searched value but not what you searched against, so normalized both to help with capitalization issues
* removed the ability to filter on last checkin time - it doesn't really make sense to filter that since those values are usually in a big state of flux (you can still sort by it though)

**Comment by timukas** [comment]
Thanks. Now filtering works much better.
