### ISSUE TITLE
User deletion not working from GUI.

### ISSUE THREAD

**Issue by timukas** [its-a-feature/Mythic#351]
Hi,

Using latest Mythic.
When new user is created and then deleted, same username cannot be created again.
Following error shown:

![md_lf_ph1_2023-12-05_22-33-56](https://github.com/its-a-feature/Mythic/assets/1915618/ef1da7dd-bc28-4ffc-bea9-372a405017f4)

It came out, that username is still in 'operator' table in Hasura.
Manually deleting user from database, allows now to create the user.

**Comment by its-a-feature** [comment]
Deleting the user doesn't actually _delete_ from the database on purpose. If you actually deleted the user from the database, then you'd lose the tracking of everything that operator did. So, if they issued a `mimikatz` command in your operation, then you deleted them, you'd lose tracking of who ran that command. Instead, Mythic (for the vast majority of things) simply has an attribute called `deleted` that gets set to `True` so that you can clean up your UI (and filter scripting queries) but that you never actually lose tracking of what happened in the system

**Comment by its-a-feature** [comment]
Ah, that's a good catch and I should update that dialog prompt. If you're an `admin`, then you don't need to know the old password. Otherwise, you would need the old password to update it.

**Comment by its-a-feature** [comment]
I've updated the wording and dialog for this and it'll get pushed in the next UI update
