### ISSUE TITLE
Mythic API returns callbacks that are related to only to current operation

### ISSUE THREAD

**Issue by XCVYN6UGT85JywuH** [its-a-feature/Mythic#362]
```
query = """
query Callbacks {
  callbacks: callback {
    id
    host
    description
    operation {
      name
    }
    payload {
      build_container
    }
    last_checkin
  }
}
"""

mythic_instance = await mythic.login(
        apitoken="token",
        server_ip=SERVER_IP,
        server_port=SERVER_PORT,
        timeout=-1
    )

query_result = await mythic.execute_custom_query(mythic=mythic_instance, query=query,
                                                     variables={"redirector": f'%{redirector}%'})
```

When i do this request, i get callbacks related only to current operation. How can i grub info about all callbacks?

**Comment by its-a-feature** [comment]
Mythic is currently configured to only fetch data based on your current operation (which is why you're seeing what you're seeing). One thing you could do is fetch all of the operations your user is a member of, then for each operation set it as your current operation, fetch the callbacks, then switch to the next operation, fetch those callbacks, etc. There's _technically_ a way to use your hasura secret from your .env to query _everything_ from the database, but that's not currently coded as part of the `mythic.login` and it's essentially the equivalent of switching to domain admin lol

**Comment by XCVYN6UGT85JywuH** [comment]
Thx
