### ISSUE TITLE
Modifying the c2 profile config.json

### ISSUE THREAD

**Issue by YuvalAsr** [its-a-feature/Mythic#364]
Hey, I have 2 mythic c2 infrastructures.
the old one has the following versions: 
[*] mythic-cli version:    v0.2.2
[*] Mythic Server version: v3.2.10
[*] React UI Version:      v0.1.45

the new one:
[*] mythic-cli version:    v0.2.9
[*] Mythic Server version: v3.2.16
[*] React UI Version:      v0.1.61

When using the older version, and the HTTP C2 profile - I configured the profile in the View/Edit Config in the GUI, to my desired port and changed use_ssl to "true".
When I restart mythic with mythic_cli, the config file returns to the default values. (in the older version it does not happen).

**Comment by its-a-feature** [comment]
In your `.env` file, do you have `REBUILD_ON_START` set to true? If so, set that to `"false"` and try again. If you don't want to do that, there should be a setting for `HTTP_USE_VOLUME` that you can set to `false`. What I believe is happening is as follows:
* In the newest Mythic, if the agent/c2 profile supports it, Mythic will configure the `docker-compose` to set the agent/c2 up with a volume (instead of a local bind mount). 
* When `REBUILD_ON_START` is `true`, Mythic will delete the agent/c2 volume on start and rebuild everything (setting it back to defaults)

This is a newer feature added in with the latest release to help ease automated deployments and reduce the number of local bind volumes.

**Comment by YuvalAsr** [comment]
The REBUILD_ON_START was set to true (probably by default), I changed it to false and it did the trick.
Thank you for the quick response!

**Comment by its-a-feature** [comment]
Glad that worked for you! I'll get that documented
