### ISSUE TITLE
error: opsec check 

### ISSUE THREAD

**Issue by Kadoronel** [its-a-feature/Mythic#377]
I encounter this error when executing a file
 upload {"remote_path":"C:\\\\Users\\\\Administrateur\\\\Downloads\\\\script.exe","file":"Missing file in form","host":"/tmp/tmp64rttosq/build/script/script"}

**Comment by its-a-feature** [comment]
I'm going to assume this is with the Apollo agent? Since Mythic runs in your web browser, it doesn't have direct access to your host file system. I'm assuming you ran something like:
```
upload /tmp/tmp64rttosq/build/script/script C:\Users\Administrateur\Downloads\script.exe
```
Instead, you need to do `upload` and then shift+enter to open up a modal so that you can select the file you want to upload and provide the path you want to use

**Comment by Kadoronel** [comment]
Ok good
