### ISSUE TITLE
Error building linux_docker on Raspbian

### ISSUE THREAD

**Issue by g4uss47** [its-a-feature/Mythic#386]
I was trying to install Mythic on a raspberry pi and since the make linux command failed i tried to install everything in docker.

After running 
`make linux_docker`
It seems that it also tries to build it for macos and subsequently fails  
```
Step 9/12 : RUN make build_all
 ---> Running in 45e1c482a600
go mod tidy
...
...
GOOS=linux go build -o mythic-cli_linux .
go mod tidy
GOOS=darwin go build -o mythic-cli_macos .
go: unsupported GOOS/GOARCH pair darwin/arm
make: *** [Makefile:16: build_macos] Error 2
The command '/bin/sh -c make build_all' returned a non-zero code: 2
make[1]: *** [Makefile:25: build_linux_docker] Error 2
make[1]: Leaving directory '/opt/Mythic/Mythic_CLI'
make: *** [Makefile:14: linux_docker] Error 2
```

**Comment by its-a-feature** [comment]
when you say that the "make linux command failed", can you share the error you got? When you do `make linux_docker`, it's trying to go through and recreate the mythic-cli docker container (which builds for both linux and mac) then pull out the linux binary. Something is causing an error with the arm architecture. 

As a temporary work around since you're building the mythic-cli docker container, what you could do is:
* in `Mythic/Mythic_CLI/.docker/Dockerfile` remove the last line that's copying the `mythic-cli_macos`
* in `Mythic/Mythic_CLI/src/Makefile` for the line that says `build_all:` remove the `build_macos` at the end
* try building again
That'll prevent it from trying to build the macos piece and should just do the linux aspect

The reason it builds both is because normally, the docker container has a linux and macOS version of the mythic-cli binary pre-built for you, so when you just run `sudo make` all that happens is the docker container is pulled down and the right version for your host OS is copied out of the container.

**Comment by g4uss47** [comment]
the error that i had was the one i pasted in the previous comment, this line specifically
`go: unsupported GOOS/GOARCH pair darwin/arm`

I followed your recommendations and still gives me the following error:

```
---> 0dc83a17222f
Step 12/12 : COPY --from=0 /usr/src/app/mythic-cli_macos /mythic-cli_macos
COPY failed: stat usr/src/app/mythic-cli_macos: file does not exist
```
It seems it is still trying to copy the mythic-cli_macos file after these changes applied

**Comment by its-a-feature** [comment]
oh sorry, remove the macos_copy line from `Mythic/Mythic_CLI/Dockerfile` at the bottom. Since you're building locally that's the one that's used

**Comment by g4uss47** [comment]
that was it :) now it builds successfully! 
now the issue that i am having is that it tries to pull 
```
v0.0.3.53: Pulling from its-a-feature/mythic_documentation
ERROR: no matching manifest for linux/arm/v8 in the manifest list entries
```
arm/v8 manifest instead of the arm64 version available at https://github.com/its-a-feature/Mythic/pkgs/container/mythic_documentation

However I would assume that I would need to download all of the dockers in this version instead of the missing arm/v8 right?

**Comment by its-a-feature** [comment]
ah, yeah that's going to be an issue. I can adjust my stuff to support that (most likely), but some key components don't seem like they support anything other than arm64 and amd64 (https://hub.docker.com/r/hasura/graphql-engine).
