### ISSUE TITLE
[Features]  - Extenstion for Atlas.

### ISSUE THREAD

**Issue by hayicle** [its-a-feature/Mythic#39]
Hi @its-a-feature ,

Me again ^^!. 
I'm checking if Atlas payload can support SMB named pipes like [Covenant_c2](https://github.com/cobbr/Covenant) so we can implement the P-2-P [C2 Profile](https://docs.mythic-c2.net/c2-profiles/egress-vs-p2p#p-2-p-profiles). 

Good to hear your opinions ^^!.
Thanks in advance.

**Comment by airzero24** [comment]
Unfortunately, I've moved on to other projects and only work on Atlas for bug fixes. It's completely possible to implement a SMB p2p protocol within Atlas, but would take a lot of work to get a full message bus working. Since this was just a pet project to help me learn C#, it's very disorganized and not ideal to work with.

That being said, your absolutely welcome to write the code for a p2p protocol yourself and I'll happily review any PR's to add to the Atlas codebase.

**Comment by hayicle** [comment]
Thanks FYI ^^!.

**Comment by hayicle** [comment]
Hi @airzero24, 

Just 1 more question, how about the reusable of [Covenant code base](https://github.com/cobbr/Covenant/blob/79c45e77e95b4010f9676e34aacae3d18bbb5df0/Covenant/API/Models/Grunt.cs
) or any fit interaction between Covenant and Mythic (components)?

**Comment by its-a-feature** [comment]
Closing this because it's stale. Atlas specific issues can be opened here: https://github.com/MythicAgents/atlas
