### ISSUE TITLE
Why is there a tmp permission? Has anyone installed it successfully?

### ISSUE THREAD

**Issue by rustxj** [its-a-feature/Mythic#392]
`root@xt:~/Mythic# sudo ./mythic-cli install github https://github.com/MythicAgents/Athena
2024/07/23 15:07:46 [-] Error while reading in docker-compose file: Config File "docker-compose" Not Found in "[/tmp]"
2024/07/23 15:07:46 [-] Failed to read in new docker-compose.yml file: Config File "docker-compose" Not Found in "[/tmp]"
2024/07/23 15:07:46 [-] Error while reading in docker-compose file: Config File "docker-compose" Not Found in "[/tmp]"
root@AMSTEAM:~/Mythic# `

The tutorials on YouTube and GitHub seem to be different versions, and the tutorials in the documentation are also different from GitHub. This simple docker has become so complicated. Has anyone encountered this problem?

**Comment by rustxj** [comment]
root@xt:~/Mythic# ./mythic-cli start
2024/07/23 15:07:46 [-] Error while reading in docker-compose file: Config File "docker-compose" Not Found in "[/tmp]"
2024/07/23 15:07:46 [-] Failed to read in new docker-compose.yml file: Config File "docker-compose" Not Found in "[/tmp]"
2024/07/23 15:07:46 [-] Error while reading in docker-compose file: Config File "docker-compose" Not Found in "[/tmp]"
root@xt:~/Mythic#

**Comment by rustxj** [comment]
![image](https://github.com/user-attachments/assets/ccb21c47-acf4-4236-8391-3264a19931d5)

**Comment by its-a-feature** [comment]
I don't think I've ever seen those errors before. Can you provide a bit more information?
* what OS are you installing this on?
* how did you install Mythic (which branch)?
* is this a fresh install or an upgrade?

The docs (https://docs.mythic-c2.net/installation) is always the most up to date

**Comment by rustxj** [comment]
Google Cloud

**Comment by its-a-feature** [comment]
Where is mythic installed and where are you running these commands from? Are you doing it all from the same context? It appears as though mythic is installed in one location, but it keeps looking to the `/tmp` directory. Nothing in Mythic explicitly tries to do anything with the `/tmp` directory, which is why that's strange. Unless that's where you installed Mythic and are running `mythic-cli` from? `mythic-cli` should be looking for `docker-compose.yml` in the same directory where `mythic-cli` is located

**Comment by its-a-feature** [comment]
If you're still having this issue, we can reopen it, but since I haven't heard from you in a while I'm going to close this for now
