### ISSUE TITLE
[Feature Request] Privileged Container 

### ISSUE THREAD

**Issue by charnim** [its-a-feature/Mythic#407]
I have a custom agent that relies on a Docker Inside Docker architecture. 
Having the ability to install the custom agent with /mythic-cli install folder ./MyAgent -f --privileged or something of 
the sort would be a neat upgrade.

**Comment by its-a-feature** [comment]
I don't publicize this much because it doesn't happen very often, but you can actually already do that. In your `config.json` that's part of your repo / folder that's used when you install, you can include the following:
```
"docker-compose": {
        "privileged": true
    }
```
^ the `docker-compose` key and then a key-value dictionary of what things you need set in docker compose for which fields. Hermes actually does something similar so that it could use some kernel components for running Darling within Docker:

https://github.com/MythicAgents/hermes/blob/main/config.json#L7-L9

**Comment by charnim** [comment]
Ok thats useful to know,
Another thing with the install,
How can I get rid of the automatic CPU: 1 line in the docker-compose?  I want to use all cores.
