### ISSUE TITLE
runassembly stripping backslashes from arguments

### ISSUE THREAD

**Issue by tech-wit** [its-a-feature/Mythic#43]
arguments to runassembly have their backslashes stripped

e.g.  trying to run an assembly run.exe with the argument "dir c:\test", the assembly receives the following args "dir c:test"

having a crack at isolating the issue, not having much luck

**Comment by airzero24** [comment]
Hey @tech-wit,

This is most likely an issue with the janky JSON parsing I do within the agent. If you could try the following change for me to see if this is the issue, then I can update the code to reflect that. It's hard to test without the same assembly you are using since I have no idea what it's doing.

Change to be made:
within `Payload_types/atlas/agent_code/Utils.cs`
```
line 1032   Match match = new Regex(format).Match(Regex.Unescape(data));
```

Please let me know if this fixes your issue and I'll update the rest of the code and submit a PR to master for it.

**Comment by tech-wit** [comment]
hey nice one, you nailed it, need to also patch the following line in the same file to the following

`line 1035    if (match.Groups["group1"] != null) { matches.Add(Regex.Unescape(match.Groups["group1"].Value)); }`

Thanks for the help

**Comment by its-a-feature** [comment]
@airzero24 You should be good now to use the 2.2-updates branch in Mythic with the https://github.com/MythicAgents/atlas code to do your updates for this and for the upload/loadassembly stuff.
