### ISSUE TITLE
Impossible to install via folder after cloning Apollo agent and rebased with my own repo

### ISSUE THREAD

**Issue by ZZ0R0** [its-a-feature/Mythic#430]
I have for bad habit to first clone the repo that i want to edit, then edit it then create my own repo and finally rebase it to my own url, it's what i did for the CEOS agent and it worked well

I did the same for Apollo agent and it didn't worked
To avoid confusions inside Mythic i've renamed it "artemis"

when i try to install it via the cli using sudo mythic-cli install folder /my/agent/folder/path it gives me the following error => 

elz@Vx30 ~/cyber/Agents/Artemis
 % sudo mcli install folder /home/elz/cyber/Agents/Artemis -f
2024/11/17 10:14:02 [*] Parsing config.json
2024/11/17 10:14:02 [*] Processing Payload Type artemis
2024/11/17 10:14:02 [*] Stopping current container
2024/11/17 10:14:02 [*] Removing current version
2024/11/17 10:14:02 [+] Successfully removed the current version
2024/11/17 10:14:02 [*] Copying new version of payload into place
2024/11/17 10:14:03 [*] Adding service into docker-compose
2024/11/17 10:14:03 [*] Container not running: artemis
[+] Running 1/1
 ✘ artemis Error Head "https://ghcr.io/v2/mythicagents/artemis/manifests/v0.0.0.12": denied0.5s 
 
 
 
 i've checked absolutely all the files contained inside the repo, i've searched either using copilot so he find me where is this defined but nothing to do i don't find where is the section declared
 
 i first thought it was present inside config.json, so i deleted the line, nothing changed
 then i thought it could be inside .github/workflows/docker.yml, so i deleted the file, nothing changed
 
 i'm pretty stuck with this at the moment and so i don't understand how can i properly fork the Apollo repo to suite my needs
 
 (basically i've just implemented "real" sRDI instead of donut)

**Comment by its-a-feature** [comment]
Since you already tried installing once and then starting modifying things, I think what you're seeing is a mixture of data (partial Apollo, partial Artemis). Look in your `.env` file, you'll likely see an entry for your new `artemis` like this:
```
ARTEMIS_INSTALL_LOCATION="https://github.com/mythicagents/apollo;master"
ARTEMIS_REMOTE_IMAGE="ghcr.io/mythicagents/apollo:v0.0.0.14"
ARTEMIS_USE_BUILD_CONTEXT="true"
```
That entry in your `.env` will come from when you install an agent that has in their config.json an entry like this (https://github.com/MythicAgents/Apollo/blob/master/config.json#L8). My guess is that you initially tried installing without modifying that (since the other agent probably doesn't have it), then you removed it, but didn't remove it from the `.env` file. You should be good to just delete those three entries from your `.env` file and try installing again

**Comment by its-a-feature** [comment]
Did that work for you?

**Comment by its-a-feature** [comment]
I'm going to close this for now, but if that didn't end up working for you, please comment on here and we can reopen it
