### ISSUE TITLE
Deleted Payload

### ISSUE THREAD

**Issue by dvlpsup** [its-a-feature/Mythic#52]
Hi,

Not sure that it is on purpose or not but when you delete a created payload, a payload already deployed can still connect to the Mythic Server. The result of deleting a payload should not be like a payload that never existed, UUID not known/allowed to connect to the Mythic Server?

Version of Mythic: 2.1.17

Thx

**Comment by its-a-feature** [comment]
hm... So you're wanting a way to temporarily or permanently block the UUID for the payload from creating new callbacks? I think that should be something a bit different than deleting a payload so that you have a recover capability. Right now, deleting a payload does a few things:

- removes it from that "Created Payloads" page
- prevents it from popping up as an option when creating wrapper payloads
- prevents it from popping up as an option when spawning new payloads

I think it would be nice to have the ability to toggle payloads to allow/prevent them from connecting dynamically. That way you could even block a "compromised" payload from connecting in. 

Good feedback - I'll try to incorporate something related to this in the next update

**Comment by dvlpsup** [comment]
Hi Cody,

Thank you very much for the answer. It is clear now what happens when a payload is deleted.
Indeed an option allow/prevent is a really good idea.

Regards

**Comment by its-a-feature** [comment]
The 2.2 update will prevent deleted payloads from being able to make new callbacks 👍
