### ISSUE TITLE
The field is not displayed

### ISSUE THREAD

**Issue by Strannik74** [its-a-feature/Mythic#86]
Hello!
I'm a newbie
Installed v2.1.18 because I couldn't start v2.2.7
An empty field is reflected.
What's my mistake..?
![Снимок экрана от 2021-07-03 18-03-23](https://user-images.githubusercontent.com/31668854/124355128-14765000-dc29-11eb-8215-eabe9aa71d2e.png)

**Comment by its-a-feature** [comment]
In 2.2.* there are no C2 Profiles or Payload Types included by default, you'd have to explicitly install them via `mythic-cli install github <url>` where the agents are located at `https://github.com/MythicAgents` and the c2 profiles are located at `https://github.com/MythicC2Profiles` .  In 2.1.*, the C2 Profiles and Agents are included locally. To help see what's going on though, I'll need more information.

- What error were you getting before when you couldn't start 2.2.7?
- What's the output of `mythic-cli status` (if you're on 2.2.7 or `./status_check.sh` if you're on 2.1.*)

**Comment by Strannik74** [comment]
Hello!
./status_check.sh 2.1
![05 07](https://user-images.githubusercontent.com/31668854/124427538-f1f94980-dd84-11eb-8c52-98655f2ffe34.png)

2.2.7
![Снимок экрана от 2021-07-05 11-38-26](https://user-images.githubusercontent.com/31668854/124428013-98dde580-dd85-11eb-8ff4-591c48f75db8.png)



./mythic-cli status
![Снимок экрана от 2021-07-05 11-33-13](https://user-images.githubusercontent.com/31668854/124427615-0e958180-dd85-11eb-9d7d-357be71eed77.png)

**Comment by its-a-feature** [comment]
In your 2.1 screenshot, there appears to be an issue with your rabbitmq container (notice how it's restarting). Can you look at the output of that container to see what the error is (`sudo ./display_output.sh mythic_rabbitmq`)? With that container down, no messages would be able to make it from the containers to the main Mythic server, which would explain why your agent list is empty.

In your 2.2 screenshot - did you stop your Mythic 2.1 instance first? It's saying that the postgres port appears to already be in use, so it can't even start it, which is why the status shows nothing running.

**Comment by its-a-feature** [comment]
The new mythic-cli binary will notice that there's no agents or c2 profiles installed and give you commands you can run to install agents/c2 profiles as well as telling you where to get them from to help with this issue.
