### ISSUE TITLE
Error with latest update dynamic http with a custom c2 profile

### ISSUE THREAD

**Issue by ineffectivecoder** [its-a-feature/Mythic#91]
Hello,
We've been playing with the latest release of Mythic and have noticed some odd errors in the Live Feed.
We're configuring a listener with Dynamic HTTP with a custom profile.
We receive the following error in the live feed consistently:
```
Failed to correlate UUID, lSTJKlngDKjWDgrnBRWBUUBeYXnxPB, to something mythic knows
Connection to: http://somesomesomething.com/jquery-3.3.1.map?q=NzUyZmY1N2UtYzZlZS00OTk0LWIzNzQtYWEyYmI4YWFhNWRjGzGybt5K30V72cDE6soyL4P7BOhvZTDjR2WxG5MvMNRuwmeRP037Dg8p3Y1ZS6gMt%2FOkTGtwqFkQbl4Eg5NcUdsiIAVxbMCco%2Fu61ZfG0BIlC7UasK1Ye37lF3Yp8gQy via GET
From: 1.1.1.1(hidden to protect the innocent)
With extra headers: <Header('host': 'somesomesomething.com', 'mythic': 'http', 'connection': 'close', 'x-forwarded-for': '1.1.1.1', 'x-forwarded-host': 'somesomesomething.comg', 'x-forwarded-proto': 'https', 'x-forwarded-ssl': 'on', 'x-real-ip': '1.1.1.1', 'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'cookie': '__cfduid=bFNUSktsbmdES2pXRGdybkJSV0JVVUJlWVhueFBC;', 'user-agent': 'BLAHBLAHBLAH', 'accept-language': 'en-us', 'referer': 'http://blahblahblah.com/', 'accept-encoding': 'gzip, deflate', 'x-forwarded-url': 'somesomesomething.com/jquery-3.3.1.map?q=NzUyZmY1N2UtYzZlZS00OTk0LWIzNzQtYWEyYmI4YWFhNWRjGzGybt5K30V72cDE6soyL4P7BOhvZTDjR2WxG5MvMNRuwmeRP037Dg8p3Y1ZS6gMt%2FOkTGtwqFkQbl4Eg5NcUdsiIAVxbMCco%2Fu61ZfG0BIlC7UasK1Ye37lF3Yp8gQy', 'x-forwarded-query': 'q=NzUyZmY1N2UtYzZlZS00OTk0LWIzNzQtYWEyYmI4YWFhNWRjGzGybt5K30V72cDE6soyL4P7BOhvZTDjR2WxG5MvMNRuwmeRP037Dg8p3Y1ZS6gMt%2FOkTGtwqFkQbl4Eg5NcUdsiIAVxbMCco%2Fu61ZfG0BIlC7UasK1Ye37lF3Yp8gQy', 'x-forwarded-port': '80', 'x-forwarded-cookies': "{'__cfduid': 'bFNUSktsbmdES2pXRGdybkJSV0JVVUJlWVhueFBC'}")>
```
While this does not appear to impact the traffic from the beacon, it is a curious error message that we're not sure what to do with.

Thanks.

**Comment by its-a-feature** [comment]
Hey! I can definitely do a better job at explaining some context around those messages for sure. 

So, in general, the "Failed to correlate UUID" message means that data came in through some C2 Profile, made its way to Mythic, Mythic base64 decoded the data successfully and looked at the first characters for a UUID. In Mythic messages, the only piece that's normally not encrypted is this random UUID4 string in the front that means something to Mythic, but is generally meaningless to everybody else. Mythic uses that UUID to look up the callback/payload/stage crypto keys and other related information for processing. In this case though, the UUID that Mythic sees isn't registered within Mythic's database. Normally people see this because they have old agents still connecting in, but they've since reset their database. In your case though, that's not _actually_ a UUID4. So, that means some other data got in. 

Looking at the rest of the message, we can see additional data. All C2 Profile docker containers add an additional header when forwarding messages to the Mythic server with `mythic: c2profile_name`. So, in this case we see `'mythic': 'http'` which means that the `http` profile is forwarding this message along to the Mythic server. What's odd is that this message looks a lot like your dynamichttp data, which should be going through your dynamichttp container. That would explain why Mythic isn't seeing a UUID, but rather some piece of encoded data that should have been transformed away as part of the dynamichttp profile.

So, I would check your configs and make sure that you're not accidentally also sending (or still sending from some previous testing) your dynamichttp data through your http container. That would also explain why your callbacks aren't affected because some of your data is still going through your dynamichttp container and being transformed properly.

Does that help?
